-- ISOLATED ONLY: fixture publication/state changes roll back. Tested RPCs, RLS,
-- permissions and triggers are the actual application definitions.
BEGIN;
DO $$ BEGIN IF current_setting('dc.recovery_mode',true) IS DISTINCT FROM 'isolated' THEN RAISE EXCEPTION 'Isolated recovery only'; END IF; END $$;
SET LOCAL statement_timeout='30s';
CREATE TEMP TABLE hf AS SELECT gen_random_uuid() actor,gen_random_uuid() other_actor,gen_random_uuid() guardian,gen_random_uuid() home,gen_random_uuid() other_home,gen_random_uuid() product;
CREATE TEMP TABLE hc(label text PRIMARY KEY,session_id uuid,order_id uuid,attempt_id uuid);
CREATE TEMP TABLE hr(label text);
GRANT SELECT ON hf TO authenticated,anon,service_role;
GRANT SELECT,INSERT,UPDATE ON hc TO authenticated;
GRANT SELECT ON hc TO anon,service_role;
GRANT SELECT,INSERT ON hr TO authenticated,anon,service_role;
CREATE FUNCTION pg_temp.ok(value boolean,label text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF value IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: %',label; END IF; INSERT INTO hr VALUES(label); END $$;
CREATE FUNCTION pg_temp.denied(command text,expected text,label text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 BEGIN EXECUTE command; EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE expected THEN RAISE; END IF; INSERT INTO hr VALUES(label); RETURN; END;
 RAISE EXCEPTION 'Unexpected success: %',label;
END $$;
CREATE FUNCTION pg_temp.stage(label text) RETURNS void LANGUAGE plpgsql AS $$ DECLARE c record; a record; BEGIN
 SELECT r.* INTO c FROM hf f CROSS JOIN LATERAL public.create_checkout_order(f.home,jsonb_build_array(jsonb_build_object('product_id',f.product)),NULL) r;
 SELECT * INTO a FROM public.claim_checkout_provider_handoff(c.checkout_session_id,'synthetic');
 IF a.disposition<>'invoke_adapter' THEN RAISE EXCEPTION 'New checkout not claimed'; END IF;
 INSERT INTO hc VALUES(label,c.checkout_session_id,c.order_id,a.attempt_id);
END $$;
GRANT EXECUTE ON FUNCTION pg_temp.ok(boolean,text),pg_temp.denied(text,text,text) TO authenticated,anon,service_role;
GRANT EXECUTE ON FUNCTION pg_temp.stage(text) TO authenticated;
INSERT INTO auth.users(id,raw_app_meta_data,raw_user_meta_data) SELECT actor,'{}'::jsonb,'{}'::jsonb FROM hf UNION ALL SELECT other_actor,'{}'::jsonb,'{}'::jsonb FROM hf UNION ALL SELECT guardian,'{}'::jsonb,'{}'::jsonb FROM hf;
INSERT INTO public.households(id,name,created_by) SELECT home,'Synthetic handoff',actor FROM hf UNION ALL SELECT other_home,'Synthetic foreign handoff',other_actor FROM hf;
INSERT INTO public.household_members(household_id,user_id,role,status) SELECT home,guardian,'guardian','active' FROM hf;
SET LOCAL session_replication_role=replica;
INSERT INTO public.products(id,product_key,name,product_type,status,base_price_cents,track_inventory) SELECT product,product::text,'Synthetic handoff product','other','active',123,false FROM hf;
SET LOCAL session_replication_role=origin;
SELECT set_config('request.jwt.claim.sub',actor::text,true) FROM hf;
SET LOCAL ROLE authenticated;
SELECT pg_temp.stage(label) FROM unnest(ARRAY['primary','expired','canceled','paid','bad_order_owner','bad_order_home','bad_session_home','removed','adult','conflict','failure','duplicate_ref']) label;
SELECT pg_temp.ok((SELECT count(*)=12 FROM hc),'Guardian creates and claims fresh checkouts');
SELECT pg_temp.ok((SELECT disposition='awaiting_result' FROM hc c CROSS JOIN LATERAL public.claim_checkout_provider_handoff(c.session_id,'synthetic') WHERE c.label='primary'),'Duplicate claim never authorizes another dispatch');
SELECT pg_temp.denied(format('SELECT public.claim_checkout_provider_handoff(%L,%L)',session_id,'other'),'%already claimed','Conflicting provider cannot replace claim') FROM hc WHERE label='primary';
SELECT pg_temp.denied(format('SELECT public.begin_checkout_provider_handoff(%L,%L,%L)',session_id,'synthetic','forged'),'Matching provider result required','Guardian cannot invent provider receipt') FROM hc WHERE label='primary';
SELECT pg_temp.denied(format('SELECT public.record_checkout_handoff_result(%L,%L,%L)',attempt_id,'forged','https://provider.invalid/'),'permission denied%','Receipt API is service-only') FROM hc WHERE label='primary';
SELECT pg_temp.denied('SELECT * FROM private.checkout_handoff_attempts','permission denied%','Private attempt table hidden from guardian');
WITH changed AS (UPDATE public.checkout_sessions SET status='provider_pending',provider_checkout_id='forged',payment_provider='synthetic' WHERE id IN (SELECT session_id FROM hc) RETURNING id) SELECT pg_temp.ok((SELECT count(*)=0 FROM changed),'Direct guardian provider/session writes denied');
WITH changed AS (UPDATE public.orders SET status='paid',total_cents=0 WHERE id IN (SELECT order_id FROM hc) RETURNING id) SELECT pg_temp.ok((SELECT count(*)=0 FROM changed),'Direct paid/total writes denied');
SELECT pg_temp.denied(format('INSERT INTO public.household_entitlement_grants(household_id,entitlement_key,source_type) VALUES(%L,%L,%L)',home,'digital_books','manual'),'permission denied%','Direct entitlement grant denied') FROM hf;
SELECT set_config('request.jwt.claim.sub',other_actor::text,true) FROM hf;
SELECT pg_temp.denied(format('SELECT public.claim_checkout_provider_handoff(%L,%L)',session_id,'synthetic'),'%unavailable or expired','Foreign household claim denied') FROM hc WHERE label='primary';
SELECT pg_temp.denied(format('SELECT private.begin_checkout_provider_handoff_impl(%L,%L,%L)',session_id,'synthetic','forged'),'%unavailable or expired','Private finalizer cannot bypass ownership') FROM hc WHERE label='primary';
SELECT pg_temp.ok(NOT EXISTS(SELECT 1 FROM public.checkout_sessions WHERE id IN (SELECT session_id FROM hc)),'Foreign handoff rows remain hidden');
SELECT set_config('request.jwt.claim.sub',guardian::text,true) FROM hf;
SELECT pg_temp.denied(format('SELECT public.claim_checkout_provider_handoff(%L,%L)',session_id,'synthetic'),'%unavailable or expired','Another guardian in same household cannot claim creator checkout') FROM hc WHERE label='primary';
SELECT set_config('request.jwt.claim.sub','',true);
SELECT pg_temp.denied(format('SELECT private.claim_checkout_provider_handoff_impl(%L,%L)',session_id,'synthetic'),'Authentication required','Private claim requires Auth identity') FROM hc WHERE label='primary';
RESET ROLE;
SET LOCAL ROLE anon;
SELECT pg_temp.denied(format('SELECT public.claim_checkout_provider_handoff(%L,%L)',session_id,'synthetic'),'permission denied%','Anonymous claim denied') FROM hc WHERE label='primary';
SELECT pg_temp.denied(format('SELECT public.begin_checkout_provider_handoff(%L,%L,%L)',session_id,'synthetic','forged'),'permission denied%','Anonymous finalization denied') FROM hc WHERE label='primary';
RESET ROLE;
SET LOCAL request.jwt.claims='{"role":"service_role"}';
SET LOCAL ROLE service_role;
SELECT pg_temp.denied('SELECT * FROM private.digital_book_manifests','permission denied%','Service namespace USAGE confers no existing private table access');
SELECT pg_temp.denied('SELECT * FROM private.checkout_handoff_attempts','permission denied%','Service receipt API confers no direct attempt table access');
SELECT public.record_checkout_handoff_result(attempt_id,'ref-'||session_id,'https://provider.invalid/'||session_id) FROM hc WHERE label<>'failure';
SELECT public.record_checkout_handoff_result(attempt_id,p_failure_code:='adapter_unavailable') FROM hc WHERE label='failure';
SELECT pg_temp.ok(true,'Trusted service records receipts or diagnostic failure only');
SELECT pg_temp.denied(format('SELECT public.record_checkout_handoff_result(%L,%L,%L)',attempt_id,'changed','https://provider.invalid/changed'),'Handoff result already recorded','Recorded provider receipt immutable') FROM hc WHERE label='primary';
RESET ROLE;
SET LOCAL request.jwt.claims='{}';
SELECT set_config('request.jwt.claim.sub',actor::text,true) FROM hf;
SET LOCAL ROLE authenticated;
SELECT pg_temp.ok((SELECT disposition='finalize' FROM hc c CROSS JOIN LATERAL public.claim_checkout_provider_handoff(c.session_id,'synthetic') WHERE c.label='primary'),'Recorded receipt retry requests local finalization only');
SELECT public.begin_checkout_provider_handoff(session_id,'synthetic','ref-'||session_id) FROM hc WHERE label='primary';
SELECT pg_temp.ok((SELECT cs.status='provider_pending' AND o.status='pending_payment' AND cs.order_id=c.order_id AND cs.household_id=o.household_id AND cs.user_id=o.purchaser_user_id AND cs.provider_checkout_id='ref-'||cs.id AND o.total_cents=123 AND o.paid_at IS NULL AND cs.expires_at=now()+interval '30 minutes' FROM hc c JOIN public.checkout_sessions cs ON cs.id=c.session_id JOIN public.orders o ON o.id=c.order_id WHERE c.label='primary'),'Authorized handoff atomically preserves binding, total, expiry and unpaid status');
SELECT public.begin_checkout_provider_handoff(session_id,'synthetic','ref-'||session_id) FROM hc WHERE label='primary';
SELECT pg_temp.ok((SELECT disposition='reuse' FROM hc c CROSS JOIN LATERAL public.claim_checkout_provider_handoff(c.session_id,'synthetic') WHERE c.label='primary'),'Repeated finalized handoff reuses reference without dispatch');
SELECT pg_temp.denied(format('SELECT public.begin_checkout_provider_handoff(%L,%L,%L)',session_id,'synthetic','changed'),'Matching provider result required','Finalized reference cannot be changed') FROM hc WHERE label='primary';
SELECT pg_temp.ok((SELECT disposition='awaiting_result' FROM hc c CROSS JOIN LATERAL public.claim_checkout_provider_handoff(c.session_id,'synthetic') WHERE c.label='failure'),'Adapter failure retains non-dispatching reconciliation claim');
SELECT pg_temp.ok((SELECT cs.status='created' AND o.status='draft' FROM hc c JOIN public.checkout_sessions cs ON cs.id=c.session_id JOIN public.orders o ON o.id=c.order_id WHERE c.label='failure'),'Adapter failure cannot mark successful handoff');
RESET ROLE;
UPDATE public.checkout_sessions SET expires_at=now()-interval '1 second' WHERE id=(SELECT session_id FROM hc WHERE label='expired');
UPDATE public.checkout_sessions SET status='canceled' WHERE id=(SELECT session_id FROM hc WHERE label='canceled');
UPDATE public.orders SET status='paid' WHERE id=(SELECT order_id FROM hc WHERE label='paid');
UPDATE public.orders SET purchaser_user_id=(SELECT other_actor FROM hf) WHERE id=(SELECT order_id FROM hc WHERE label='bad_order_owner');
UPDATE public.orders SET household_id=(SELECT other_home FROM hf) WHERE id=(SELECT order_id FROM hc WHERE label='bad_order_home');
UPDATE public.checkout_sessions SET household_id=(SELECT other_home FROM hf) WHERE id=(SELECT session_id FROM hc WHERE label='bad_session_home');
UPDATE public.orders SET status='canceled' WHERE id=(SELECT order_id FROM hc WHERE label='conflict');
SET LOCAL ROLE authenticated;
SELECT pg_temp.denied(format('SELECT public.claim_checkout_provider_handoff(%L,%L)',session_id,'synthetic'),'%unavailable or expired','Claim denies '||label) FROM hc WHERE label IN ('expired','canceled','paid','bad_order_owner','bad_order_home','bad_session_home','conflict');
SELECT pg_temp.denied(format('SELECT public.begin_checkout_provider_handoff(%L,%L,%L)',session_id,'synthetic','ref-'||session_id),'%unavailable or expired','Finalize denies '||label) FROM hc WHERE label IN ('expired','canceled','paid','bad_order_owner','bad_order_home','bad_session_home','conflict');
RESET ROLE;
UPDATE public.household_members SET status='removed' WHERE household_id=(SELECT home FROM hf) AND user_id=(SELECT actor FROM hf);
SET LOCAL ROLE authenticated;
SELECT pg_temp.denied(format('SELECT public.claim_checkout_provider_handoff(%L,%L)',session_id,'synthetic'),'%unavailable or expired','Removed membership cannot claim') FROM hc WHERE label='removed';
SELECT pg_temp.denied(format('SELECT public.begin_checkout_provider_handoff(%L,%L,%L)',session_id,'synthetic','ref-'||session_id),'%unavailable or expired','Removed membership cannot finalize') FROM hc WHERE label='removed';
RESET ROLE;
UPDATE public.household_members SET status='active',role='adult' WHERE household_id=(SELECT home FROM hf) AND user_id=(SELECT actor FROM hf);
SET LOCAL ROLE authenticated;
SELECT pg_temp.denied(format('SELECT public.claim_checkout_provider_handoff(%L,%L)',session_id,'synthetic'),'%unavailable or expired','Non-guardian adult cannot claim owned checkout') FROM hc WHERE label='adult';
SELECT pg_temp.denied(format('SELECT public.begin_checkout_provider_handoff(%L,%L,%L)',session_id,'synthetic','ref-'||session_id),'%unavailable or expired','Non-guardian adult cannot finalize owned checkout') FROM hc WHERE label='adult';
RESET ROLE;
UPDATE public.household_members SET role='owner' WHERE household_id=(SELECT home FROM hf) AND user_id=(SELECT actor FROM hf);
-- Simulate a conflicting provider reference; uniqueness failure must roll back both state writes.
UPDATE private.checkout_handoff_attempts SET provider_checkout_id=(SELECT 'ref-'||session_id FROM hc WHERE label='primary') WHERE id=(SELECT attempt_id FROM hc WHERE label='duplicate_ref');
SET LOCAL ROLE authenticated;
SELECT pg_temp.denied(format('SELECT public.begin_checkout_provider_handoff(%L,%L,%L)',session_id,'synthetic',(SELECT 'ref-'||session_id FROM hc WHERE label='primary')),'duplicate key value violates unique constraint%','Duplicate provider reference rolls back transition') FROM hc WHERE label='duplicate_ref';
SELECT pg_temp.ok((SELECT cs.status='created' AND o.status='draft' AND cs.provider_checkout_id IS NULL FROM hc c JOIN public.checkout_sessions cs ON cs.id=c.session_id JOIN public.orders o ON o.id=c.order_id WHERE c.label='duplicate_ref'),'Failed finalization leaves no partial order/session mutation');
RESET ROLE;
SELECT pg_temp.ok((SELECT state='result_ready' FROM private.checkout_handoff_attempts WHERE id=(SELECT attempt_id FROM hc WHERE label='duplicate_ref')),'Provider receipt survives failed finalization for reconciliation');
-- Synthetic callback uses unchanged service-only payment validation and replay path.
SET LOCAL request.jwt.claims='{"role":"service_role"}';
SET LOCAL ROLE service_role;
SELECT public.mark_order_paid_from_provider(p_order_id:=order_id,p_provider:='synthetic',p_provider_payment_id:='pay-'||order_id,p_provider_event_id:='evt-'||order_id,p_payload:=jsonb_build_object('provider_checkout_id','ref-'||session_id,'amount_cents',123::bigint,'currency','USD')) FROM hc WHERE label='primary';
SELECT public.mark_order_paid_from_provider(p_order_id:=order_id,p_provider:='synthetic',p_provider_payment_id:='pay-'||order_id,p_provider_event_id:='evt-'||order_id,p_payload:=jsonb_build_object('provider_checkout_id','ref-'||session_id,'amount_cents',123::bigint,'currency','USD')) FROM hc WHERE label='primary';
SELECT pg_temp.ok((SELECT cs.status='completed' AND o.status='paid' FROM hc c JOIN public.checkout_sessions cs ON cs.id=c.session_id JOIN public.orders o ON o.id=c.order_id WHERE c.label='primary') AND (SELECT count(*)=1 FROM public.payment_webhook_events WHERE order_id=(SELECT order_id FROM hc WHERE label='primary')),'Existing callback succeeds after new handoff and replay commits once');
RESET ROLE;
SET LOCAL request.jwt.claims='{}';
SET LOCAL ROLE authenticated;
SELECT pg_temp.denied(format('SELECT public.begin_checkout_provider_handoff(%L,%L,%L)',session_id,'synthetic','ref-'||session_id),'%unavailable or expired','Paid checkout cannot reenter handoff') FROM hc WHERE label='primary';
RESET ROLE;
SELECT pg_temp.ok((SELECT count(*)=0 FROM pg_policies WHERE schemaname='public' AND tablename='checkout_sessions' AND cmd IN ('UPDATE','ALL')),'No guardian UPDATE policy introduced');
SELECT count(*) AS handoff_checks_passed FROM hr;
SELECT * FROM hr;
ROLLBACK;
