-- Dependency-aware client ACL hardening. Reviewed source matrix: docs/security/CLIENT_PRIVILEGE_MATRIX.md.
-- No application rows, policies, triggers, schedules, providers, or historical migrations are changed.
-- Hosted postgres cannot ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin; see platform blocker.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';
REVOKE ALL ON ALL TABLES IN SCHEMA public, private FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public, private FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public, private FROM PUBLIC, anon, authenticated, service_role;
-- Content inspection and membership-status helpers must respect caller RLS; nested owner calls retain owner rights.
ALTER FUNCTION private.dc_entity_payload(text,uuid) SECURITY INVOKER;
ALTER FUNCTION private.dc_entity_fingerprint(text,uuid) SECURITY INVOKER;
ALTER FUNCTION private.household_is_paid_member(uuid) SECURITY INVOKER;
-- Existing column-only group membership restriction is preserved below.
GRANT SELECT ON TABLE public.achievement_token_ledger TO authenticated;
GRANT INSERT, SELECT ON TABLE public.adventure_groups TO authenticated;
GRANT SELECT, UPDATE ON TABLE public.adventures TO authenticated;
GRANT SELECT ON TABLE public.app_admins TO authenticated;
GRANT SELECT ON TABLE public.app_channel_health TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.app_installations TO authenticated;
GRANT SELECT ON TABLE public.badge_awards TO authenticated;
GRANT INSERT, SELECT ON TABLE public.badge_rules TO authenticated;
GRANT INSERT, SELECT ON TABLE public.badges TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.book_challenges TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.book_content_links TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.book_devotional_series TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.book_identity_truths TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.book_power_verses TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.book_prayer_prompts TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.book_reward_rules TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.books TO authenticated;
GRANT SELECT, UPDATE ON TABLE public.challenge_assignments TO authenticated;
GRANT INSERT, SELECT ON TABLE public.challenge_series TO authenticated;
GRANT INSERT, SELECT ON TABLE public.challenge_steps TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.challenges TO authenticated;
GRANT SELECT ON TABLE public.checkout_session_summary TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.checkout_sessions TO authenticated;
GRANT SELECT ON TABLE public.child_active_streak_badges TO authenticated;
GRANT SELECT ON TABLE public.child_activity_events TO authenticated;
GRANT SELECT ON TABLE public.child_adventure_progress TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.child_book_progress TO authenticated;
GRANT SELECT ON TABLE public.child_book_reading_positions TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.child_challenge_progress TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.child_content_progress TO authenticated;
GRANT SELECT ON TABLE public.child_data_inventory TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.child_devotional_progress TO authenticated;
GRANT SELECT ON TABLE public.child_group_memberships TO authenticated;
GRANT UPDATE (status, ended_at) ON TABLE public.child_group_memberships TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.child_identity_progress TO authenticated;
GRANT SELECT ON TABLE public.child_level_progress TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.child_prayer_progress TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.child_profiles TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.child_scripture_progress TO authenticated;
GRANT SELECT ON TABLE public.child_series_streak_status TO authenticated;
GRANT SELECT ON TABLE public.child_series_streaks TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.child_step_progress TO authenticated;
GRANT SELECT ON TABLE public.child_streaks TO authenticated;
GRANT SELECT ON TABLE public.child_token_totals TO authenticated;
GRANT SELECT ON TABLE public.child_xp_totals TO authenticated;
GRANT SELECT ON TABLE public.commerce_readiness_summary TO authenticated;
GRANT SELECT ON TABLE public.commerce_recent_webhooks TO authenticated;
GRANT SELECT ON TABLE public.consent_policies TO authenticated;
GRANT SELECT, UPDATE ON TABLE public.contact_inquiries TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.content_items TO authenticated;
GRANT SELECT ON TABLE public.current_household_consents TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.data_privacy_requests TO authenticated;
GRANT SELECT ON TABLE public.dc_blueprint_requirements TO authenticated;
GRANT SELECT ON TABLE public.dc_brand_assets TO authenticated;
GRANT SELECT ON TABLE public.dc_character_profiles TO authenticated;
GRANT SELECT ON TABLE public.dc_content_blueprints TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.dc_content_reviews TO authenticated;
GRANT SELECT ON TABLE public.dc_governance_entity_catalog TO authenticated;
GRANT SELECT ON TABLE public.dc_governance_review_status TO authenticated;
GRANT SELECT ON TABLE public.dc_governance_rules TO authenticated;
GRANT SELECT ON TABLE public.dc_governance_standards TO authenticated;
GRANT SELECT ON TABLE public.delivery_worker_health TO authenticated;
GRANT SELECT ON TABLE public.delivery_worker_runs TO authenticated;
GRANT INSERT, SELECT ON TABLE public.devotional_days TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.devotional_series TO authenticated;
GRANT SELECT ON TABLE public.entitlement_definitions TO authenticated;
GRANT SELECT ON TABLE public.event_registrations TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.events TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.family_faith_guides TO authenticated;
GRANT SELECT ON TABLE public.fulfillments TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.group_challenge_assignments TO authenticated;
GRANT INSERT, SELECT ON TABLE public.household_consents TO authenticated;
GRANT SELECT ON TABLE public.household_entitlement_grants TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.household_faith_sessions TO authenticated;
GRANT SELECT, UPDATE ON TABLE public.household_invitations TO authenticated;
GRANT SELECT ON TABLE public.household_members TO authenticated;
GRANT SELECT ON TABLE public.household_membership_summary TO authenticated;
GRANT SELECT ON TABLE public.household_subscriptions TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.households TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.identity_truths TO authenticated;
GRANT SELECT ON TABLE public.integration_events TO authenticated;
GRANT SELECT ON TABLE public.integration_health_summary TO authenticated;
GRANT SELECT ON TABLE public.integration_latest_tests TO authenticated;
GRANT SELECT ON TABLE public.integration_providers TO authenticated;
GRANT SELECT ON TABLE public.integration_test_runs TO authenticated;
GRANT INSERT, SELECT ON TABLE public.inventory_reservations TO authenticated;
GRANT SELECT ON TABLE public.levels TO authenticated;
GRANT SELECT, UPDATE ON TABLE public.marketing_leads TO authenticated;
GRANT INSERT, SELECT ON TABLE public.media_assets TO authenticated;
GRANT SELECT ON TABLE public.membership_plans TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.notification_campaigns TO authenticated;
GRANT SELECT ON TABLE public.notification_deliveries TO authenticated;
GRANT SELECT ON TABLE public.notification_delivery_health TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.notification_preferences TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.notification_reminder_rules TO authenticated;
GRANT INSERT, SELECT ON TABLE public.notification_templates TO authenticated;
GRANT INSERT, SELECT ON TABLE public.order_items TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.orders TO authenticated;
GRANT SELECT, UPDATE ON TABLE public.organization_invitations TO authenticated;
GRANT SELECT ON TABLE public.organization_members TO authenticated;
GRANT INSERT, SELECT ON TABLE public.organizations TO authenticated;
GRANT SELECT ON TABLE public.parent_child_progress_summary TO authenticated;
GRANT SELECT ON TABLE public.payment_webhook_events TO authenticated;
GRANT SELECT ON TABLE public.plan_entitlements TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.power_verses TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.prayer_prompts TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.product_book_access_rules TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.product_entitlement_rules TO authenticated;
GRANT SELECT ON TABLE public.product_variants TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.products TO authenticated;
GRANT SELECT, UPDATE ON TABLE public.profiles TO authenticated;
GRANT INSERT, SELECT ON TABLE public.promo_codes TO authenticated;
GRANT SELECT ON TABLE public.public_site_pipeline_summary TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.push_devices TO authenticated;
GRANT SELECT ON TABLE public.referral_attributions TO authenticated;
GRANT SELECT ON TABLE public.referral_codes TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.reward_redemptions TO authenticated;
GRANT SELECT ON TABLE public.reward_unlocks TO authenticated;
GRANT INSERT, SELECT ON TABLE public.rewards TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.scripture_passages TO authenticated;
GRANT INSERT, SELECT ON TABLE public.series_badge_rules TO authenticated;
GRANT SELECT ON TABLE public.streak_badge_earnings TO authenticated;
GRANT INSERT, SELECT, UPDATE ON TABLE public.support_tickets TO authenticated;
GRANT SELECT, UPDATE ON TABLE public.user_notifications TO authenticated;
GRANT SELECT ON TABLE public.xp_ledger TO authenticated;
GRANT EXECUTE ON FUNCTION private.accept_household_invitation_impl(p_invitation_id uuid, p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.accept_organization_invitation_impl(p_invitation_id uuid, p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.admin_daily_metrics_impl(p_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION private.admin_get_book_launch_gate_impl() TO authenticated;
GRANT EXECUTE ON FUNCTION private.admin_get_book_release_gate_impl() TO authenticated;
GRANT EXECUTE ON FUNCTION private.admin_get_digital_book_impl(p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.admin_get_digital_book_launch_gate_impl() TO authenticated;
GRANT EXECUTE ON FUNCTION private.admin_get_membership_tier_gate_impl() TO authenticated;
GRANT EXECUTE ON FUNCTION private.admin_get_production_launch_gate_impl() TO authenticated;
GRANT EXECUTE ON FUNCTION private.admin_platform_snapshot_impl() TO authenticated;
GRANT EXECUTE ON FUNCTION private.admin_prepare_digital_book_impl(p_book_id uuid, p_manifest jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION private.attribute_referral_impl(p_code text, p_referred_household_id uuid, p_source text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.award_completed_book_adventure(p_child_profile_id uuid, p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_approve_dc_governance() TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_lead_group(p_group_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_manage_challenge_progress(p_progress_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_manage_child(p_child_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_manage_event(p_event_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_manage_household(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_manage_org(p_organization_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_manage_privacy_requests() TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_record_child_activity(p_child_id uuid, p_content_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_schedule_notifications() TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_view_child(p_child_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_view_event(p_event_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.cancel_event_registration_impl(p_registration_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.child_can_access_challenge(p_child_profile_id uuid, p_challenge_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.child_has_book_companion_access(p_child_profile_id uuid, p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.claim_marketing_leads_for_household_impl(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.create_group_join_code_impl(p_group_id uuid, p_expires_in_days integer, p_max_uses integer) TO authenticated;
GRANT EXECUTE ON FUNCTION private.create_guardian_unlock_session_impl(p_household_id uuid, p_pin text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.create_household_invitation_impl(p_household_id uuid, p_email text, p_role text, p_expires_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION private.create_organization_invitation_impl(p_organization_id uuid, p_email text, p_organization_role text, p_group_id uuid, p_group_role text, p_expires_in_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION private.dc_entity_fingerprint(p_entity_type text, p_entity_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.dc_entity_payload(p_entity_type text, p_entity_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.dc_row_fingerprint(p_payload jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION private.digital_book_object_readable(p_path text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.get_digital_book_impl(p_child_profile_id uuid, p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.get_group_progress_summary_impl(p_group_id uuid, p_challenge_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.get_group_roster_impl(p_group_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.get_household_adults_impl(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.get_or_create_referral_code_impl(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.guardian_pin_status_impl(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.guardian_unlock_session_valid(p_household_id uuid, p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.has_approved_dc_review(p_entity_type text, p_entity_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.household_has_active_entitlement(p_household_id uuid, p_entitlement_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.household_is_paid_member(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_app_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_content_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_household_member(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_operations_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_org_member(p_organization_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.join_child_to_group_impl(p_code text, p_child_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.notification_audience_count_impl(p_audience_type text, p_membership_plan_id uuid, p_household_id uuid, p_organization_id uuid, p_group_id uuid, p_event_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.preview_group_join_code_impl(p_code text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.preview_organization_invitation_impl(p_invitation_id uuid, p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.privacy_export_payload_impl(p_request_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.register_for_event_impl(p_event_id uuid, p_household_id uuid, p_child_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.save_digital_book_position_impl(p_child_profile_id uuid, p_book_id uuid, p_revision text, p_page_number integer) TO authenticated;
GRANT EXECUTE ON FUNCTION private.set_guardian_pin_impl(p_household_id uuid, p_pin text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.user_has_active_entitlement(p_entitlement_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.user_has_book_access(p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.user_has_household() TO authenticated;
GRANT EXECUTE ON FUNCTION private.verify_guardian_pin_impl(p_household_id uuid, p_pin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_household_invitation(p_invitation_id uuid, p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_organization_invitation(p_invitation_id uuid, p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_add_devotional_day(p_series_id uuid, p_day_number integer, p_title text, p_body text, p_scripture_id uuid, p_prayer_prompt text, p_action_step text, p_xp_reward integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cancel_notification_campaign(p_campaign_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_book(p_book_number integer, p_title text, p_slug text, p_description text, p_cover_asset_key text, p_release_date date, p_status text, p_completion_xp integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_challenge(p_title text, p_slug text, p_challenge_type text, p_description text, p_instructions text, p_access_level text, p_xp_reward integer, p_parent_approval_required boolean, p_status text, p_steps jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_challenge_series(p_series_key text, p_name text, p_description text, p_token_type text, p_token_amount integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_content_item(p_content_type text, p_title text, p_slug text, p_summary text, p_category text, p_asset_key text, p_thumbnail_asset_key text, p_access_level text, p_status text, p_is_featured boolean, p_completion_xp integer, p_body jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_devotional_series(p_title text, p_slug text, p_description text, p_access_level text, p_status text, p_is_featured boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_family_faith_guide(p_guide_key text, p_title text, p_book_id uuid, p_description text, p_scripture_passage_id uuid, p_discussion_prompt text, p_prayer_prompt text, p_family_action text, p_access_level text, p_status text, p_sort_order integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_identity_truth(p_title text, p_slug text, p_statement text, p_explanation text, p_scripture_id uuid, p_say_it text, p_sort_order integer, p_access_level text, p_status text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_lifetime_badge_level(p_badge_key text, p_name text, p_rule_type text, p_threshold_value integer, p_description text, p_badge_family_key text, p_tier text, p_rarity text, p_streak_key text, p_challenge_type text, p_token_type text, p_activity_event_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_notification_reminder_rule(p_rule_key text, p_name text, p_rule_type text, p_template_id uuid, p_lead_minutes integer, p_delivery_channels text[], p_organization_id uuid, p_group_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_notification_template(p_template_key text, p_name text, p_notification_type text, p_title text, p_body text, p_deep_link text, p_priority text, p_default_channels text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_organization(p_organization_key text, p_name text, p_organization_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_power_verse(p_scripture_id uuid, p_title text, p_slug text, p_explanation text, p_say_it text, p_live_it text, p_give_it_away text, p_memorize_xp integer, p_access_level text, p_status text, p_is_featured boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_prayer_prompt(p_title text, p_slug text, p_prompt_text text, p_category text, p_scripture_id uuid, p_xp_reward integer, p_access_level text, p_status text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_product(p_product_key text, p_name text, p_product_type text, p_description text, p_sku text, p_base_price_cents integer, p_member_price_cents integer, p_status text, p_track_inventory boolean, p_inventory_quantity integer, p_allow_backorder boolean, p_is_featured boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_promo_code(p_code text, p_description text, p_discount_type text, p_discount_value integer, p_starts_at timestamp with time zone, p_ends_at timestamp with time zone, p_max_redemptions integer, p_minimum_order_cents integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_reward(p_reward_key text, p_name text, p_description text, p_reward_type text, p_xp_required integer, p_access_level text, p_inventory_quantity integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_scripture(p_reference text, p_translation text, p_verse_text text, p_theme_key text, p_status text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_series_streak_badge(p_series_id uuid, p_badge_key text, p_name text, p_consecutive_weeks integer, p_description text, p_tier text, p_rarity text, p_active_only_while_current_streak boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_weekly_challenge(p_series_id uuid, p_title text, p_slug text, p_period_start date, p_description text, p_challenge_type text, p_access_level text, p_xp_reward integer, p_parent_approval_required boolean, p_status text, p_steps jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_daily_metrics(p_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_digital_book(p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_platform_snapshot() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_production_launch_gate() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_link_book_experience(p_book_id uuid, p_item_type text, p_item_id uuid, p_sort_order integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_link_book_reward(p_book_id uuid, p_reward_id uuid, p_milestone text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_prepare_digital_book(p_book_id uuid, p_manifest jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_preview_notification_audience(p_audience_type text, p_membership_plan_id uuid, p_household_id uuid, p_organization_id uuid, p_group_id uuid, p_event_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_schedule_notification_campaign(p_campaign_key text, p_name text, p_template_id uuid, p_audience_type text, p_scheduled_at timestamp with time zone, p_delivery_channels text[], p_membership_plan_id uuid, p_household_id uuid, p_organization_id uuid, p_group_id uuid, p_event_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_order_status(p_order_id uuid, p_status text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_dc_content_review(p_review_id uuid, p_creative_alignment boolean, p_word_of_faith_alignment boolean, p_scripture_verified boolean, p_identity_in_christ_alignment boolean, p_child_age_appropriate boolean, p_church_affirming boolean, p_approved_assets_only boolean, p_character_continuity boolean, p_language_style_pass boolean, p_notes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_parent_challenge(p_progress_id uuid, p_guardian_session_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.archive_child_profile(p_child_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.attribute_referral(p_code text, p_referred_household_id uuid, p_source text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.begin_checkout_provider_handoff(p_checkout_session_id uuid, p_provider text, p_provider_checkout_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_data_privacy_request(p_request_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_event_registration(p_registration_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_organization_invitation(p_invitation_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.capture_marketing_lead(p_lead_type text, p_source_page text, p_parent_guardian_name text, p_email text, p_child_first_name text, p_child_age smallint, p_parent_guardian_consent boolean, p_marketing_consent boolean, p_consent_text text, p_ip_hash text, p_user_agent_hash text, p_metadata jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_marketing_leads_for_household(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.claim_notification_deliveries(p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_child_book_adventure(p_child_profile_id uuid, p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_family_faith_participants(p_household_id uuid, p_guide_id uuid, p_child_ids uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_notification_delivery(p_delivery_id uuid, p_status text, p_provider text, p_provider_message_id text, p_last_error text, p_retry_minutes integer, p_metadata jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_adventure_group(p_organization_id uuid, p_group_key text, p_name text, p_group_type text, p_description text, p_minimum_age smallint, p_maximum_age smallint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_checkout_order(p_household_id uuid, p_items jsonb, p_promo_code text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_child_with_consent(p_household_id uuid, p_display_name text, p_birth_year smallint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_group_join_code(p_group_id uuid, p_expires_in_days integer, p_max_uses integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_guardian_unlock_session(p_household_id uuid, p_pin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_household_invitation(p_household_id uuid, p_email text, p_role text, p_expires_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_household_with_consent(p_name text, p_timezone text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_organization_invitation(p_organization_id uuid, p_email text, p_organization_role text, p_group_id uuid, p_group_role text, p_expires_in_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.dc_preflight_scan(p_entity_type text, p_entity_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_checkout_readiness() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_child_achievement_progress(p_child_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_child_book_adventure_steps(p_child_profile_id uuid, p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_child_book_adventure_summary(p_child_profile_id uuid, p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_digital_book(p_child_profile_id uuid, p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_group_progress_summary(p_group_id uuid, p_challenge_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_group_roster(p_group_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_household_adults(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_notification_delivery_payload(p_delivery_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_or_create_referral_code(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.guardian_pin_status(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_book_access(p_book_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.join_child_to_group(p_code text, p_child_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_order_paid_from_provider(p_order_id uuid, p_provider text, p_provider_payment_id text, p_provider_customer_id text, p_provider_event_id text, p_event_type text, p_shipping_name text, p_shipping_address jsonb, p_payload jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.preview_group_join_code(p_code text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.preview_organization_invitation(p_invitation_id uuid, p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.privacy_export_payload(p_request_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.publish_dc_entity(p_entity_type text, p_entity_id uuid, p_target_status text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_household_consent(p_household_id uuid, p_consent_key text, p_action text, p_child_profile_id uuid, p_metadata jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_integration_event(p_provider_key text, p_event_type text, p_direction text, p_entity_type text, p_entity_id uuid, p_status text, p_idempotency_key text, p_request_payload jsonb, p_response_payload jsonb, p_last_error text) TO service_role;
GRANT EXECUTE ON FUNCTION public.register_app_installation(p_installation_key text, p_app_channel text, p_platform text, p_app_version text, p_device_name text, p_push_provider text, p_push_token text, p_capabilities jsonb, p_metadata jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.register_for_event(p_event_id uuid, p_household_id uuid, p_child_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.request_data_privacy_action(p_household_id uuid, p_request_type text, p_child_profile_id uuid, p_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.request_dc_content_review(p_entity_type text, p_entity_id uuid, p_notes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.restore_child_profile(p_child_profile_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.return_parent_challenge(p_progress_id uuid, p_guardian_session_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_guardian_unlock_sessions(p_household_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_household_invitation(p_invitation_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_digital_book_position(p_child_profile_id uuid, p_book_id uuid, p_revision text, p_page_number integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_family_challenge_participants(p_household_id uuid, p_challenge_id uuid, p_child_ids uuid[], p_action text, p_step_ids uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_guardian_pin(p_household_id uuid, p_pin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_integration_provider_health(p_provider_key text, p_status text, p_health_status text, p_success boolean, p_error text) TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_worker_token(p_token_key text, p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.verify_guardian_pin(p_household_id uuid, p_pin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_privacy_cleanup_secret(p_secret text) TO service_role;
GRANT EXECUTE ON FUNCTION public.withdraw_child_from_group(p_group_id uuid, p_child_profile_id uuid) TO authenticated;
-- Per-schema defaults are additive. Revoke global PUBLIC EXECUTE as well as explicit schema grants.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM PUBLIC, anon, authenticated;
-- Existing service_role and platform-owner defaults are retained. New client exposure requires explicit reviewed grants.
NOTIFY pgrst, 'reload schema';
