-- Read-only application catalog capture. No household, child, Auth, or secret data.
set search_path='';
select jsonb_build_object(
 'server_version',current_setting('server_version'),
 'extensions',(select jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname) order by e.extname) from pg_extension e join pg_namespace n on n.oid=e.extnamespace),
 'schemas',(select jsonb_agg(jsonb_build_object('name',n.nspname,'owner',pg_get_userbyid(n.nspowner),'acl',n.nspacl::text) order by n.nspname) from pg_namespace n where n.nspname in ('public','private')),
 'types',(select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',t.typname,'kind',t.typtype,'enum_labels',(select jsonb_agg(e.enumlabel order by e.enumsortorder) from pg_enum e where e.enumtypid=t.oid),'base',format_type(t.typbasetype,t.typtypmod),'not_null',t.typnotnull,'default',t.typdefault) order by n.nspname,t.typname),'[]'::jsonb) from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname in ('public','private') and t.typtype in ('e','d')),
 'relations',(select jsonb_agg(jsonb_build_object(
  'schema',n.nspname,'name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),
  'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'replica_identity',c.relreplident,
  'options',c.reloptions,'acl',c.relacl::text,'comment',obj_description(c.oid,'pg_class'),
  'view_definition',case when c.relkind in ('v','m') then pg_get_viewdef(c.oid,true) end,
  'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid),'acl',a.attacl::text,'comment',col_description(c.oid,a.attnum),'identity_sequence',case when a.attidentity<>'' then pg_get_serial_sequence(format('%I.%I',n.nspname,c.relname),a.attname) end) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),
  'constraints',(select jsonb_agg(jsonb_build_object('name',k.conname,'type',k.contype,'definition',pg_get_constraintdef(k.oid,true),'validated',k.convalidated) order by k.conname) from pg_constraint k where k.conrelid=c.oid),
  'indexes',(select jsonb_agg(jsonb_build_object('name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'constraint_backed',exists(select 1 from pg_constraint k where k.conindid=i.indexrelid)) order by ic.relname) from pg_index i join pg_class ic on ic.oid=i.indexrelid where i.indrelid=c.oid)
 ) order by n.nspname,c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind in ('r','p','v','m')),
 'sequences',(select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'type',format_type(s.seqtypid,null),'start',s.seqstart::text,'increment',s.seqincrement::text,'min',s.seqmin::text,'max',s.seqmax::text,'cache',s.seqcache::text,'cycle',s.seqcycle,'owned_by',(select jsonb_build_object('schema',tn.nspname,'table',tc.relname,'column',a.attname,'dependency',d.deptype) from pg_depend d join pg_class tc on tc.oid=d.refobjid join pg_namespace tn on tn.oid=tc.relnamespace join pg_attribute a on a.attrelid=tc.oid and a.attnum=d.refobjsubid where d.classid='pg_class'::regclass and d.objid=c.oid and d.deptype in ('a','i') limit 1)) order by n.nspname,c.relname),'[]'::jsonb) from pg_sequence s join pg_class c on c.oid=s.seqrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private')),
 'functions',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'identity_args',pg_get_function_identity_arguments(p.oid),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'definition',pg_get_functiondef(p.oid),'comment',obj_description(p.oid,'pg_proc')) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prokind in ('f','p')),
 'triggers',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid,true)) order by n.nspname,c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid join pg_namespace pn on pn.oid=p.pronamespace where not t.tgisinternal and (n.nspname in ('public','private') or pn.nspname in ('public','private'))),
 'policies',(select jsonb_agg(to_jsonb(p) order by p.schemaname,p.tablename,p.policyname) from pg_policies p where p.schemaname in ('public','private','storage')),
 'view_dependencies',(select coalesce(jsonb_agg(distinct jsonb_build_object('view_schema',vn.nspname,'view',v.relname,'depends_schema',dn.nspname,'depends',dc.relname)),'[]'::jsonb) from pg_rewrite r join pg_class v on v.oid=r.ev_class join pg_namespace vn on vn.oid=v.relnamespace join pg_depend d on d.objid=r.oid and d.classid='pg_rewrite'::regclass join pg_class dc on dc.oid=d.refobjid and d.refclassid='pg_class'::regclass join pg_namespace dn on dn.oid=dc.relnamespace where vn.nspname in ('public','private') and v.relkind in ('v','m') and dc.relkind in ('v','m') and dc.oid<>v.oid),
 'default_privileges',(select coalesce(jsonb_agg(jsonb_build_object('owner',pg_get_userbyid(d.defaclrole),'schema',n.nspname,'type',d.defaclobjtype,'acl',d.defaclacl::text) order by pg_get_userbyid(d.defaclrole),n.nspname,d.defaclobjtype),'[]'::jsonb) from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace where n.nspname in ('public','private')),
 'event_triggers',(select coalesce(jsonb_agg(jsonb_build_object('name',e.evtname,'event',e.evtevent,'owner',pg_get_userbyid(e.evtowner),'enabled',e.evtenabled,'tags',e.evttags,'function',p.oid::regprocedure::text)),'[]'::jsonb) from pg_event_trigger e join pg_proc p on p.oid=e.evtfoid join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')),
 'publication_tables',(select coalesce(jsonb_agg(to_jsonb(t) order by t.pubname,t.schemaname,t.tablename),'[]'::jsonb) from pg_publication_tables t where t.schemaname in ('public','private')),
 'buckets',(select jsonb_agg(jsonb_build_object('id',b.id,'name',b.name,'public',b.public,'file_size_limit',b.file_size_limit,'allowed_mime_types',b.allowed_mime_types) order by b.id) from storage.buckets b)
) as catalog;
