#!/usr/bin/env python3
"""Render the reviewed catalog capture, without contacting any database.

Historical migrations are evidence only; this generator does not replay them.
Fails on unsupported catalog features instead of silently omitting them.
"""
import csv
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def ident(value):
    return '"' + value.replace('"', '""') + '"'


def literal(value):
    return 'NULL' if value is None else "'" + str(value).replace("'", "''") + "'"


def qualified(item):
    return ident(item['schema']) + '.' + ident(item['name'])


def acl_entries(value):
    if value is None:
        return None
    result = []
    for item in next(csv.reader([value[1:-1]])):
        if not item:
            continue
        grantee, rest = item.split('=', 1)
        privileges, grantor = rest.rsplit('/', 1)
        result.append((grantee or 'PUBLIC', privileges, grantor))
    return result


PRIVILEGES = dict(r='SELECT', a='INSERT', w='UPDATE', d='DELETE', D='TRUNCATE',
                  x='REFERENCES', t='TRIGGER', m='MAINTAIN', X='EXECUTE',
                  U='USAGE', C='CREATE')


def role(name):
    return 'PUBLIC' if name == 'PUBLIC' else ident(name)


def privileges_sql(entries, target, prefix='GRANT ', suffix='', column=None):
    lines = []
    for grantee, privileges, _ in entries:
        for index, code in enumerate(privileges):
            if code == '*':
                continue
            permission = PRIVILEGES[code]
            if column:
                permission += ' (' + ident(column) + ')'
            option = ' WITH GRANT OPTION' if privileges[index + 1:index + 2] == '*' else ''
            lines.append(f'{prefix}{permission} ON {target} TO {role(grantee)}{option}{suffix};')
    return lines


def render():
    c = json.loads((ROOT / 'catalog.json').read_text())
    assert not c['types'], 'Add reviewed rendering for new custom types'
    assert not c['event_triggers'] and not c['publication_tables']
    tables = [r for r in c['relations'] if r['kind'] == 'r']
    views = [r for r in c['relations'] if r['kind'] == 'v']
    assert len(tables) + len(views) == len(c['relations'])
    assert all(r['replica_identity'] == 'd' for r in tables)
    assert all(not a['generated'] for r in tables for a in r['columns'])
    seqs = {(s['schema'], s['name']): s for s in c['sequences']}
    assert all(s['owned_by']['dependency'] == 'i' for s in seqs.values())
    roles = {'PUBLIC', 'postgres', 'supabase_admin', 'anon', 'authenticated', 'service_role'}
    for item in [*c['schemas'], *c['relations'], *c['sequences'], *c['functions'], *c['default_privileges']]:
        roles.update(x[0] for x in acl_entries(item['acl']) or [])
    recipients = ', '.join(role(r) for r in sorted(roles))
    lines = [
        '-- GENERATED by generate.py from the read-only 2026-09-26 catalog capture.',
        '-- ISOLATED RECOVERY ONLY. Includes explicitly inventoried legacy ACLs.',
        '-- No production data, credentials, history repair or active schedules.',
        'BEGIN;',
        "SET LOCAL search_path = '';",
        'SET LOCAL check_function_bodies = false;',
        'SET LOCAL statement_timeout = 0;',
        "DO $guard$ BEGIN\n"
        " IF current_setting('dc.recovery_mode', true) IS DISTINCT FROM 'isolated' THEN\n"
        "  RAISE EXCEPTION 'Use the isolated recovery runner';\n END IF;\n"
        " IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace\n"
        "  WHERE n.nspname IN ('public','private') AND c.relkind IN ('r','p','v','m','S')\n"
        "  AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid='pg_class'::regclass\n"
        "   AND d.objid=c.oid AND d.deptype='e')) THEN\n"
        "  RAISE EXCEPTION 'Refusing a populated application schema';\n END IF;\nEND $guard$;",
        'CREATE SCHEMA IF NOT EXISTS private AUTHORIZATION postgres;',
    ]
    for schema in c['schemas']:
        lines.append(f'ALTER SCHEMA {ident(schema["name"])} OWNER TO {ident(schema["owner"])};')
    lines += ['\n-- Tables first; defaults/checks referencing application functions follow them.']
    for r in tables:
        columns = []
        for a in r['columns']:
            col = ident(a['name']) + ' ' + a['type']
            if a['identity']:
                s = next(s for s in seqs.values() if s['owned_by']['schema'] == r['schema']
                         and s['owned_by']['table'] == r['name'] and s['owned_by']['column'] == a['name'])
                mode = 'ALWAYS' if a['identity'] == 'a' else 'BY DEFAULT'
                options = f'SEQUENCE NAME {qualified(s)} START WITH {s["start"]} INCREMENT BY {s["increment"]} MINVALUE {s["min"]} MAXVALUE {s["max"]} CACHE {s["cache"]}'
                if s['cycle']:
                    options += ' CYCLE'
                col += f' GENERATED {mode} AS IDENTITY ({options})'
            if a['not_null']:
                col += ' NOT NULL'
            columns.append(col)
        lines.append(f'CREATE TABLE {qualified(r)} (\n  ' + ',\n  '.join(columns) + '\n);')
        if r['options']:
            lines.append(f'ALTER TABLE {qualified(r)} SET (' + ', '.join(r['options']) + ');')
    lines += ['\n-- Current deployed functions; no obsolete historical definitions are replayed.']
    for f in c['functions']:
        lines.append(f['definition'].rstrip().rstrip(';') + ';')
    lines += ['\n-- Views in dependency order.']
    pending = {(v['schema'], v['name']): v for v in views}
    while pending:
        ready = [k for k in pending if not any((d['depends_schema'], d['depends']) in pending
                 for d in c['view_dependencies'] if (d['view_schema'], d['view']) == k)]
        assert ready, 'Cyclic view dependency needs review'
        for key in sorted(ready):
            v = pending.pop(key)
            options = ' WITH (' + ', '.join(v['options']) + ')' if v['options'] else ''
            lines.append(f'CREATE VIEW {qualified(v)}{options} AS\n' + v['view_definition'].rstrip().rstrip(';') + ';')
    lines += ['\n-- Defaults, primary/unique/check constraints, then foreign keys and indexes.']
    for r in tables:
        for a in r['columns']:
            if a['default'] is not None and not a['identity']:
                lines.append(f'ALTER TABLE {qualified(r)} ALTER COLUMN {ident(a["name"])} SET DEFAULT {a["default"]};')
    for foreign in (False, True):
        for r in tables:
            for k in r['constraints'] or []:
                if (k['type'] == 'f') == foreign:
                    lines.append(f'ALTER TABLE {qualified(r)} ADD CONSTRAINT {ident(k["name"])} {k["definition"]};')
    for r in tables:
        for idx in r['indexes'] or []:
            if not idx['constraint_backed']:
                lines.append(idx['definition'] + ';')
    lines += ['\n-- Auth and application triggers, RLS and policies.']
    for t in c['triggers']:
        lines.append(t['definition'] + ';')
        state = {'D': 'DISABLE', 'R': 'ENABLE REPLICA', 'A': 'ENABLE ALWAYS', 'O': 'ENABLE'}[t['enabled']]
        if state != 'ENABLE':
            lines.append(f'ALTER TABLE {ident(t["schema"])}.{ident(t["table"])} {state} TRIGGER {ident(t["name"])};')
    for r in tables:
        if r['rls']:
            lines.append(f'ALTER TABLE {qualified(r)} ENABLE ROW LEVEL SECURITY;')
        if r['force_rls']:
            lines.append(f'ALTER TABLE {qualified(r)} FORCE ROW LEVEL SECURITY;')
    for p in c['policies']:
        line = f'CREATE POLICY {ident(p["policyname"])} ON {ident(p["schemaname"])}.{ident(p["tablename"])} AS {p["permissive"]} FOR {p["cmd"]} TO '
        line += ', '.join(role('PUBLIC' if x == 'public' else x) for x in p['roles'])
        if p['qual'] is not None:
            line += ' USING (' + p['qual'] + ')'
        if p['with_check'] is not None:
            line += ' WITH CHECK (' + p['with_check'] + ')'
        lines.append(line + ';')
    lines += ['\n-- Captured owners and effective ACLs. See docs/recovery/LEGACY_GRANTS.md.']
    for kind, items in [('SCHEMA', c['schemas']), ('TABLE', c['relations']),
                        ('SEQUENCE', c['sequences']), ('FUNCTION', c['functions'])]:
        for item in items:
            name = ident(item['name']) if kind == 'SCHEMA' else qualified(item)
            if kind == 'FUNCTION':
                name += '(' + item['identity_args'] + ')'
            lines.append(f'ALTER {kind} {name} OWNER TO {ident(item["owner"])};')
            entries = acl_entries(item['acl'])
            if entries is None:
                # PostgreSQL NULL ACL means owner defaults (plus PUBLIC for functions).
                codes = {'SCHEMA': 'UC', 'TABLE': 'arwdDxtm', 'SEQUENCE': 'rwU', 'FUNCTION': 'X'}[kind]
                entries = [(item['owner'], codes, item['owner'])]
                if kind == 'FUNCTION':
                    entries.append(('PUBLIC', 'X', item['owner']))
            target = kind + ' ' + name
            lines.append(f'REVOKE ALL ON {target} FROM {recipients};')
            lines += privileges_sql(entries, target)
            if item.get('comment') is not None:
                lines.append(f'COMMENT ON {target} IS {literal(item["comment"])};')
            if kind == 'TABLE':
                for a in item['columns']:
                    if a['acl'] is not None:
                        lines += privileges_sql(acl_entries(a['acl']), target, column=a['name'])
                    if a['comment'] is not None:
                        lines.append(f'COMMENT ON COLUMN {name}.{ident(a["name"])} IS {literal(a["comment"])};')
    lines += ['\n-- Historical default ACLs retained explicitly for isolated fidelity, pending hardening.']
    for d in c['default_privileges']:
        target = {'r': 'TABLES', 'S': 'SEQUENCES', 'f': 'FUNCTIONS'}[d['type']]
        prefix = f'ALTER DEFAULT PRIVILEGES FOR ROLE {ident(d["owner"])} IN SCHEMA {ident(d["schema"])} '
        lines.append(prefix + f'REVOKE ALL ON {target} FROM {recipients};')
        lines += privileges_sql(acl_entries(d['acl']), target, prefix=prefix + 'GRANT ')
    lines += ['\n-- Bucket definitions only. No customer files or object rows.']
    for b in c['buckets']:
        mime = 'NULL' if b['allowed_mime_types'] is None else 'ARRAY[' + ','.join(literal(x) for x in b['allowed_mime_types']) + ']::text[]'
        lines.append('INSERT INTO storage.buckets (id,name,public,file_size_limit,allowed_mime_types) VALUES ('
                     + ','.join([literal(b['id']), literal(b['name']), str(b['public']).lower(),
                                 str(b['file_size_limit']) if b['file_size_limit'] is not None else 'NULL', mime]) + ');')
    lines.append('COMMIT;\n')
    output = '\n\n'.join(lines)
    (ROOT / 'bootstrap.sql').write_text(output)
    print(f'Generated {len(tables)} tables, {len(views)} views, {len(c["functions"])} functions; SHA256 {hashlib.sha256(output.encode()).hexdigest()}')


if __name__ == '__main__':
    render()
